services:
  web:
    image: gitlab/gitlab-ee:13.5.1-ee.0
    restart: always
    environment:
      APP_PATH: ${PATH}
      APP_HOST: ${APP_HOST}
      APP_USER: ${APP_USER}
      APP_ROOT: ${PWD}
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = ${APP_SSH_PORT}
        gitlab_rails['gitlab_default_theme'] = 2
    ports:
      - '${APP_HTTP_PORT}:80'
      - '${APP_SSH_PORT}:22'
    volumes:
      - './config:/etc/gitlab'
      - './data:/var/opt/gitlab'
      - './logs:/var/log/gitlab'
      - './hooks:/opt/gitlab/embedded/service/gitlab-rails/file_hooks/'
