services:
  web:
    image: gitlab/gitlab-ee:13.5.1-ee.0
    restart: always
    hostname: 'localhost:8080'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 2022
        gitlab_rails['gitlab_default_theme'] = 2
    ports:
      - '8080:80'
      - '2022:22'
    volumes:
      - './config:/etc/gitlab'
      - './data:/var/opt/gitlab'
      - './logs:/var/log/gitlab'
      - './embedded:/opt/gitlab/embedded'
