services:
  web:
    build:
      context: ./
    logging:
      driver: "json-file"
      options:
        max-size: 10m
    restart: always
    environment:
      APP_ROOT_USERNAME: $APP_ROOT_USERNAME
      APP_SHELL_PATH: $PATH
      APP_HOME_DIR: $PWD
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${EXTERNAL_URL}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${APP_SSH_PORT}
        gitlab_rails['gitlab_default_theme'] = 2
        gitlab_rails['env'] = {
          "APP_ROOT_USERNAME" => "${APP_ROOT_USERNAME}",
          "APP_SHELL_PATH" => "${PATH}",
          "APP_HOME_DIR" => "${PWD}"
        }
        postgresql['shared_buffers'] = "256MB"
    ports:
      - '${APP_HTTP_PORT}:80'
      - '${APP_SSH_PORT}:22'
    volumes:
      - 'data:/var/opt/gitlab'
      -  '/var/opt/gitlab/backups'
      - 'logs:/var/log/gitlab'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  data:
  logs:
